### ISSUE TITLE
Improve Server Error message

### ISSUE THREAD

**Issue by natchaiyaa** [writefreely/writefreely#684] opened 2023-04-26 04:33 UTC
Dear paperwf, i have trouble by can't post or see anything what i post. please help me to fix this matters, thank you in advance 

<img width="824" alt="Screenshot 2023-04-26 113235" src="https://user-images.githubusercontent.com/131843000/234470650-62d3a1f8-451c-4a59-a4f5-834e287af427.png">

**Comment by pylapp** [comment] 2023-04-26 12:20
Duplicate of https://github.com/writefreely/writefreely/issues/678
Duplicate of https://github.com/writefreely/writefreely/issues/683
Duplicate of https://github.com/writefreely/writefreely/issues/680

**Comment by pylapp** [comment] 2023-04-26 12:21
See this thread: https://discuss.write.as/t/cant-post-on-paper-wf/8530

**Comment by pylapp** [comment] 2023-04-27 06:47
Maybe something related to the GCP massive failure in Paris?

https://alloforfait.fr/internet/news/116878-google-cloud-incendie-globalswitch-impacte-region-francaise-nombreux-services.html

https://status.cloud.google.com/incidents/dS9ps52MUnxQfyDGPfkY#73mBtVKKfeJGJ1yaY7hV

**Comment by pylapp** [comment] 2023-04-27 11:19
Back to normal situation.

Could be nice to have better error messages and a kid of UI to contact instance admins.

**Comment by thebaer** [comment] 2023-04-27 17:22
Yes, definitely need to change that error message :smile:

I'll track that here -- will let admins set contact information and then display it on this page.

**Closed** 2023-09-22 17:08 UTC
Labels: error message
