### ISSUE TITLE
Fonts aren't applied when the network speed is low

### ISSUE THREAD

**Issue by Crocmagnon** [writefreely/writefreely#313] opened 2020-05-15 20:01 UTC
### Describe the bug
When displaying the site on a device with a low network speed, the custom fonts are loaded afterwards and aren't applied.

### Steps to reproduce (if necessary)
Use the dev tools of your browser to throttle the connection quality to 3G-like.

See [this screencast](https://cloud.augendre.info/s/pBxG5k6xdSmc4Sw).

### Expected behavior
Either fonts should be applied after being downloaded or they should not be downloaded at all. Right now it's just a waste of resource.

### Application configuration
 - **Single mode or Multi-user mode?** Single
 - **Database?** [mysql/sqlite] sqlite
 - **Open registration?** [yes/no] no
 - **Federation enabled?** [yes/no] no

**Version or last commit**: 037fc40

**Comment by voidanix** [comment] 2022-12-30 16:13
I am aware this is an old issue, but just noticed this today while refreshing a post: because the custom CSS had several font fallbacks it was really noticeable how often the wrong font was used.

This does not only apply to slow networks, though, but even extremely fast ones: if caching is disabled e.g. while logging network activity in the browser's network panel, then the issue is almost consistently reproducible (Firefox even gives a handy `downloadable font: font-display timeout, webfont not used` in the Console).

The issue, as the log above suggests, comes from [font-display](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display), added in https://github.com/writefreely/writefreely/commit/059f0d4c548c282a2385a6ef40c5ec9cc8e5a15a: reverting the commit locally fixes the issue on all the devices/browsers I have tried so far, possibly making it a candidate for a revert.

**Comment by thebaer** [comment] 2023-09-25 22:53
Yeah, I think at this point it's worth reverting that. I went ahead and did that in #774 and will get it merged. Thanks for the input!

**Closed** 2023-10-02 23:43 UTC
