### ISSUE TITLE
Install on Debian with MariaDB 10 failes

### ISSUE THREAD

**Issue by xundeenergie** [writefreely/writefreely#430] opened 2021-01-27 14:01 UTC
### Describe the bug
On Debian there is only MariaDB and no Mysql (any more). Requirement ist mysql 5.6+
MariaDB is 10.3.27
Installer can not create tables in database

### Steps to reproduce (if necessary)
1. Install on debian `apt install mariadb`
2. follow the install instructions for writefreely
3. run `writefreely config start`
4. fill out all neccessary informations
5. See the result
`2021/01/27 14:56:28 Connecting to mysql database...
ERROR: 2021/01/27 14:56:28 database.go:2631: Couldn't SHOW TABLES: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table accesstokens...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table appcontent...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table appmigrations...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table collectionattributes...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table collectionkeys...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table collectionpasswords...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table collectionredirects...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table collections...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table posts...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table remotefollows...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table remoteuserkeys...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table remoteusers...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table userattributes...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table userinvites...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table users...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Creating table usersinvited...
ERROR: 2021/01/27 14:56:28 app.go:866: commands out of sync. Did you run multiple statements at once?
2021/01/27 14:56:28 Initializing appmigrations table...
ERROR: 2021/01/27 14:56:28 app.go:575: Unable to set initial migrations: commands out of sync. Did you run multiple statements at once?`

### Expected behavior
Installer should create all tables and finish installation

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user mode
 - **Database?** [mariadb 10.3]
 - **Open registration?** [yes]
 - **Federation enabled?** [yes]

**Version or last commit**: from compiled package "writefreely_0.12.0_linux_amd64.tar.gz"

**Comment by cjeller1592** [comment] 2021-01-29 20:55
So I tried to replicate your issue on Debian with Mariadb 10.3 but was able to create all the tables & finish the installation. 

It makes me wonder if the issue is with the database setup. Have you tried setting Mariadb up again and trying the install process? I'm curious if this issue occurs again.

**Comment by thebaer** [comment] 2021-03-09 15:01
Any update on this, @xundeenergie? Anyone else seeing this issue?

**Comment by thebaer** [comment] 2021-04-07 18:55
Closing this since we can't determine if this is a bug in WriteFreely or not. Please feel free to reopen if you have any other information to add!

**Closed by thebaer** 2021-04-07 18:55 UTC
Labels: ❓ bug?
