### ISSUE TITLE
After updating to v0.13.0 /read will not load

### ISSUE THREAD

**Issue by stayinside** [writefreely/writefreely#467] opened 2021-06-12 03:33 UTC
Since updating the reader feed does not load. My reverse proxy sends a 504 and loads just hang on the debug message 
```[READ] Updating post cache```

- Multi-user mode
- sqlite
- Open registration? no
- Federation enabled? yes

**Comment by thebaer** [comment] 2021-06-17 16:29
Hi @stayinside, can you share some more information about your setup, as prompted in the original [bug report template](https://github.com/writefreely/writefreely/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)? For example, which database are you using?

And just to be sure, did you run `writefreely db migrate` after updating the binary?

**Comment by stayinside** [comment] 2021-06-17 17:17
Oh sorry my mistake!
Updated my post, and yes I definitely that.

**Comment by DaarkMoon** [comment] 2021-06-17 17:31
Same issue for me but there is a strange point:
* After a restart if go to  go to my user page (https://writefrely.example.com/user) -> It's OK
* Then I go to the read page (https://writefrely.example.com/read) -> I get an http error (504 Gateway Time-out)
* If try to go back to my user page (https://writefrely.example.com/user) -> Now I have http error (504 Gateway Time-out)

Maybe the read page lock the sqlite database ?

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user mode 
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.13.0 (last binary released for linux amd64)

PS: I have run `writefreely db migrate` after updating the binary

**Comment by thebaer** [comment] 2021-06-17 17:38
Thanks for the additional information @stayinside and @DaarkMoon -- I agree it sounds like it could be a read lock on the database. I'll try to replicate and debug more when I'm back from vacation this week. (I'm not sure what changes around the Reader query could've caused this -- it _could_ be the additional `GetCollectionAttribute` call on each blog while looping through the overall Reader results.)

**Comment by bandicootdancing** [comment] 2021-06-18 16:37
### Describe the bug
Writefreely is hanging when clicking on the reader. I'm not sure if crawlers/users are triggering the reader but writefreely is crashing daily since upgrading. I'm not sure if it's related but by the time I get around to restarting writefreely I see "too many open files." I've disabled the reader to see if the instance stays up. 

### Steps to reproduce (if necessary)
Steps to reproduce the behavior:
1. Click on reader
2. See ``[READ] Updating post cache`` in terminal
2. Writefreely becomes unusable until restart

### Application configuration
 - **Single mode or Multi-user mode?** Multi
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.13.0

**Comment by poVoq** [comment] 2021-06-26 10:30
I have a similar issue on a fresh 0.13 install (same setup as OP).

The site runs fine until I make a first post. Upon which it continues to run fine for 5 minutes or so, but the post never shows up in the /read part and soon after the entire site goes in permanent 504 timeout.

**Comment by thebaer** [comment] 2021-06-26 13:36
Thanks @poVoq, this should be fixed in #477. If anyone else can test out that branch and verify the fix, that'd be much appreciated!

**Comment by DaarkMoon** [comment] 2021-06-28 17:28
I have build binary fom branch [fix-sqlite-reader-lock](https://github.com/writefreely/writefreely/tree/fix-sqlite-reader-lock) and now it's work for me.

**Comment by thebaer** [comment] 2021-06-30 13:56
Great! Just merged that fix, and we'll release v0.13.1 later today.

**Closed by thebaer** 2021-06-30 13:56 UTC
Labels: bug
